---
- name: ansible ping for hosts with passwords
  hosts: all
  become: true
  vars_files:
    - vault.yaml
    - vars.yaml

  tasks:

    - name: Update dnf cache and packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
